name: gastronomicon

services:
  frontend:
    # The front-end builds the Svelte-Kit app and deploys it on a Node server
    build: ./app
    container_name: gastroAPP
    depends_on:
      - backend
      - database
    ports:
      - "5173:3000"
    env_file: .frontend.env
    networks:
      - front
  backend:
    # The back-end deploys the API such that it is accessible to the front-end
    image: node:25-alpine
    container_name: gastroAPI
    depends_on:
      - database
    working_dir: /home/node/app
    volumes:
      - ./api:/home/node/app
    expose:
      - "3000"
    env_file: .backend.env
    networks:
      - front
      - back
    command: node index.js
  database:
    # The database does database things fr fr
    image: postgres:latest
    restart: always
    container_name: gastroDB
    volumes:
      - dbData:/var/lib/postgresql 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # makes port accessible to the front-end
    expose:
      - "5432"
    env_file: .backend.env
    networks:
      - back

volumes:
  dbData:
networks:
  front:
    name: frontend
  back:
    name: backend
